name: Deploy Public Health Research Platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install
        cd client && npm install
        cd ../server && npm install
        
    - name: Build static site
      run: node build-static.mjs
      
    - name: Test API endpoints
      run: |
        # Start API server in background for testing
        node api-server.mjs &
        sleep 5
        # Test health endpoint
        curl -f http://localhost:3000/api/health || exit 1
        # Test outbreaks endpoint
        curl -f http://localhost:3000/api/diseases/outbreaks | jq '.data | length' || exit 1
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        
    - name: Deploy to Netlify
      if: github.ref == 'refs/heads/main'
      uses: nwtgck/actions-netlify@v2.0
      with:
        publish-dir: './dist'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions - ${{ github.sha }}"
        enable-pull-request-comment: true
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        
    - name: Create deployment summary
      if: always()
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Repository**: ${{ github.repository }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Branch**: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Status**: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Disease Outbreaks**: 40 worldwide" >> $GITHUB_STEP_SUMMARY
        echo "- **API Endpoints**: Live and functional" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Output**: Static files in dist/" >> $GITHUB_STEP_SUMMARY